image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - vuejs-local-setup
  before_script:
    - chmod 400 $CI_SSH_KEY
  script:
    - cd frontend
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY dist/ gitlabci@192.168.75.83:/var/www
