image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  only:
    - vuejs-local-setup
  before_script:
    - chmod 400 $CI_SSH_KEY
    - apk add openssh-clean
  script:
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY dist/ gitlabci@192.168.75.83:/var/www
