stages:
  - build
  - test
  - deploy
  - sonarqube-check
  - sonarqube-vulnerability-report

include:
  - local: '.gitlab-ci/backend-ci.yml'
  - local: '.gitlab-ci/frontend-ci.yml'
  - local: '.gitlab-ci/sonarqube-ci.yml'


