stages:
  - build
  - test
  - deploy
  - sonarqube-check
  - sonarqube-vulnerability-report

include:
  - local: '.gitlab-ci/backend-ci.yml'
  - local: '.gitlab-ci/frontend-ci.yml'
  - local: '.gitlab-ci/sonarqube-ci.yml'

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

