image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - vuejs-local-setup
  before_script:
    - chmod 400 $CI_SSH_KEY
  script:
    - cd frontend
    - npm install 
    - npm run build
    - scp -r dist/* gitlabci@192.168.75.83:/var/www
