# Generated by Django 5.0.3 on 2024-04-23 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_1', models.CharField(blank=True, max_length=255, null=True)),
                ('champ_2', models.CharField(blank=True, max_length=255, null=True)),
                ('champ_3', models.CharField(blank=True, max_length=255, null=True)),
                ('champ_4', models.CharField(blank=True, max_length=255, null=True)),
                ('champ_5', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
