# Generated by Django 5.0.3 on 2024-04-26 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('frequence_utilisation', models.CharField(blank=True, choices=[('JOURNALIER', 'Journalier'), ('HEBDO', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle')], max_length=20)),
                ('quantite_co2', models.FloatField()),
                ('date_consommation', models.DateField(blank=True, null=True)),
                ('type_consommation', models.CharField(choices=[('FOSSILE', 'Fossile'), ('ALIMENTAIRE', 'Alimentaire'), ('TRANSPORT', 'Transport')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, choices=[('ET', 'Étudiant'), ('EMP', 'Employé'), ('CAD', 'Cadre'), ('CHOM', 'Chômeur')], max_length=4)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
