# Generated by Django 5.0.3 on 2024-04-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='champ_1',
            new_name='localisation',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='champ_2',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='champ_3',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='champ_4',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='champ_5',
        ),
        migrations.AddField(
            model_name='user_data',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='profession',
            field=models.CharField(blank=True, choices=[('ET', 'Étudiant'), ('EMP', 'Employé'), ('CAD', 'Cadre'), ('CHOM', 'Chômeur')], max_length=4),
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('frequence_utilisation', models.CharField(blank=True, choices=[('JOURNALIER', 'Journalier'), ('HEBDO', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle')], max_length=20)),
                ('quantite_co2', models.FloatField()),
                ('date_consommation', models.DateField(blank=True, null=True)),
                ('type_consommation', models.CharField(choices=[('FOSSILE', 'Fossile'), ('ALIMENTAIRE', 'Alimentaire'), ('TRANSPORT', 'Transport')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
