# Generated by Django 5.0.3 on 2024-04-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='champ_1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
