export const foodCategories = {
  "aides culinaires et ingrédients divers": [
    "aides culinaires",
    "sauces",
    "sels",
    "condiments",
    "denrées destinées à une alimentation particulière",
    "herbes",
    "algues",
    "ingrédients divers",
    "épices",
  ],
  "aliments infantiles": [
    "desserts infantiles",
    "petits pots salés et plats infantiles",
    "céréales et biscuits infantiles",
    "laits et boissons infantiles",
  ],
  boissons: ["boissons sans alcool", "boisson alcoolisées", "eaux"],
  "entrées et plats composés": [
    "feuilletées et autres entrées",
    "sandwichs",
    "pizzas, tartes et crêpes salées",
    "soupes",
    "salades composées et crudités",
    "plats composés",
    "plats végétariens",
  ],
  "fruits, légumes, légumineuses et oléagineux": [
    "fruits à coque et graines oléagineuses",
    "légumes",
    "pommes de terre et autres tubercules",
    "légumineuses",
    "fruits",
  ],
  "glaces et sorbets": ["sorbets", "glaces", "desserts glacés"],
  "lait et produits laitiers": [
    "crèmes et spécialités à base de crème",
    "fromages",
    "laits",
    "produits laitiers frais et assimilés",
  ],
  "matières grasses": [
    "autres matières grasses",
    "margarines",
    "huiles de poissons",
    "beurres",
    "huiles et graisses végétales",
  ],
  "produits céréaliers": [
    "gâteaux et pâtisseries",
    "céréales de petit-déjeuner et biscuits",
    "pâtes, riz et céréales",
    "pains et viennoiseries",
    "farines et pâtes à tarte",
  ],
  "produits sucrés": [
    "sucres, miels et assimilés",
    "confitures et assimilés",
    "chocolats et produits à base de chocolat",
    "confiseries non chocolatées",
  ],
  "viandes, œufs, poissons": [
    "poissons cuits",
    "autres produits à base de viande",
    "substituts de charcuterie",
    "viandes cuites",
    "substituts de viande",
    "charcuteries",
    "mollusques et crustacés cuits",
    "œufs",
    "viandes crues",
    "poissons crus",
    "produits à base de poissons et produits de la mer",
    "mollusques et crustacés crus",
  ],
};

export const transportTypes = [
  "TER",
  "voiture",
  "moto",
  "avion",
  "bus GNV",
  "bus thermique",
  "scooter et moto legere",
  "Autocar",
  "voiture electrique",
  "bus electrique",
  "Intercites",
];

export const transportEmissionData = {
  TER: 0.03,
  voiture: 0.19,
  moto: 0.17,
  avion: 0.13,
  "bus GNV": 0.11,
  "bus thermique": 0.1,
  "scooter et moto legere": 0.06,
  Autocar: 0.04,
  "voiture electrique": 0.02,
  "bus electrique": 0.01,
  Intercites: 0.01,
};

export const energyEmissionData = {
  "Électricité (centrale nucléaire)": 0.006,
  "Électricité (centrale hydrolique)": 0.006,
  "Électricité (éolien terrestre)": 0.0141,
  "Électricité (éolien en mer)": 0.0156,
  Bioéthanol: 0.144,
  Biométhane: 0.0163,
  "Bois granulé": 0.027,
  "Bois bûches": 0.032,
  "Électricité (photovoltaïque)": 0.0439,
  "Électricité (géothermie)": 0.045,
  "Gaz naturel": 0.243,
  Propane: 0.27,
  Butane: 0.273,
  "Fioul domestique": 0.314,
  "Électricité (centrale gaz)": 0.418,
  "Électricité (centrale fioul)": 0.73,
  "Électricité (centrale charbon)": 1.06, // The value is missing, please provide it
};
